import { ContextProvider } from "@/stores/context";
import { UnstatedCounter, UnstatedForm } from "@/stores/unstated";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContextProvider>
        <RecoilRoot>
          <UnstatedCounter.Provider>
            <UnstatedForm.Provider>
              <Component {...pageProps} />
            </UnstatedForm.Provider>
          </UnstatedCounter.Provider>
        </RecoilRoot>
      </ContextProvider>
    </>
  );
}
